all:
  hosts:
    node:
      ansible_host: "{{ HOST }}"
      ansible_user: "{{ USER }}"
      ansible_ssh_pass: "{{ SSH_PASS_TEST }}"
      ansible_become: yes
      ansible_sudo_pass: "{{ SUDO_PASS_TEST }}"
